### PR TITLE
Bm close order date

### PR DESCRIPTION
**Pull request by rbmccr**
RE RUN MIGRATIONS

# Description
- Completing an order adds a date to the Order table in the database for record of payment date
- Order history in user settings now shows processed date (i.e. payment date).
- Order history view also shows payment processed date

## Related Ticket(s)
#44 

## Steps to Test Solution

1. pyman test

### CODE REVIEW

**Review by jasehackman — DISMISSED** [review]
👍

**Review by kellymorin — CHANGES_REQUESTED** [review]
The date is displaying in UTC, any chance we could set a timezone there or indicate that it's UTC

**Review by kellymorin — APPROVED** [review]
👍

**Review by jasehackman — APPROVED** [review]
👍

**Pull request merged**
